### PR TITLE
switch to cooperative ctors and correct node trees to future proof

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
also helps to implement https://github.com/pytest-dev/pytest/pull/8037/

### CODE REVIEW

**Comment by asmeurer** [comment]
Should this be merged now or only after the upstream PR is done?

**Comment by RonnyPfannschmidt** [comment]
Now would be nice, it works with both variants and unblock the pr (the job against this plugin fails

**Comment by asmeurer** [comment]
Oh you have integration tests, or you are using this plugin itself to test pyflakes? Do you need me to do a release?

**Comment by RonnyPfannschmidt** [comment]
@asmeurer we use pytest-flakes as one of the plugins for the plugin compat integration tests

a release is needed

**Comment by asmeurer** [comment]
OK, I just made a 4.0.3 release. Hopefully it doesn't break things this time. I checked and the issue from https://github.com/asmeurer/pytest-flakes/issues/39 shouldn't be happening again with the 4.0.3 wheel.

**Pull request merged**
